{
    "name": "Quotation Bom",
    "version": "11.0",
    "depends": ["sale", 'website_quote', 'website'],
    "data": [
        "security/security_group.xml",
        "views/quotation_bom_views.xml",
        "views/formula.xml",
        "views/transaction.xml",
        "views/product_product_views.xml",
        "views/sale_order_views.xml",
        'views/quotation_template.xml',
        # 'views/template.xml',
        "views/quotation_bom_menus_views.xml",
        "views/sale_order_schedule_views.xml",
        "wizard/quote_line_add_item.xml",
        "wizard/quote_line_mass_edit_views.xml",
        "report/commerical_proposal_main_menu.xml",
        "report/commerical_proposal_template.xml",
        "report/sale_order_menu.xml",
        "report/annexure_template.xml",
        "report/annexure_main_menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
